### PR TITLE
API: provide all versions supported in plugin api call

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
You can't do this, this break the API, so old BTCPay Server (and current one) will list all the versions as is on the plugins page, making the page just unusable.

Can you instead just create a new SQL function to get all versions, then have a new routes whose path is `versions`?

**Comment by Kukks** [comment]
> You can't do this, this break the API, so old BTCPay Server (and current one) will list all the versions as is on the plugins page, making the plugin page unusable.
> 
> Can you instead just create a new SQL function to get all versions, then have a new routes whose path is `versions`?
> 
> You'll want to change the plugins page in btcpayserver in future version to show a drop down with all the versions.
> 
> Also, I think you don't have to returns all this data. Just a list of plugin versions (`string[]`) compatible for each plugins is enough.
> 
> This call returns basically all the database, so it won't scale, you need to return the strict minimum that make sense for the UI.

It won't, btcpay grabs the result and does a tryadd to a dictionary based on identifier

**Comment by NicolasDorier** [comment]
Also, the function is literally `get_latest_versions`, not `get_all_versions` :p

Just create a separate function/route it will save headache!

**Comment by NicolasDorier** [comment]
* Added unit test
* Kept backward compatibility and added `includeAllVersions` flag for `/plugins`

I don't think `includeAllVersions` will be available for long to be honest, the amount of data will end up being too massive when there are too many versions.

**Pull request merged**
